---

- name: Install the authorized keys for ansible deployers
  ansible.posix.authorized_key:
    user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) }}"
    key: "{{ common_dev_ops_keys | join('\n') }}"
    exclusive: "{{ common_dev_ops_keys_exclusive }}"
  tags:
    - security
