---

- name: Update hostname via hostname cmd
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Create /etc/hostname
  copy:
    content: "{{ inventory_hostname_short }}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Add hostname alias to IPv4 localhost in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{ inventory_hostname_short }}{% endif %}{{'\t'}}localhost"
    state: present

- name: Add hostname alias to IPv6 localhost in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1{{'\t\t'}}{{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{ inventory_hostname_short }}{% endif %}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state: present
