---

- name: Update hostname via hostname cmd
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: Create /etc/hostname
  ansible.builtin.copy:
    content: "{{ inventory_hostname_short }}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Add hostname alias to IPv4 localhost in /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %} {{ inventory_hostname_short }}{% endif %} localhost"
    state: present

- name: Add hostname alias to IPv6 localhost in /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1 {{ inventory_hostname }}{% if inventory_hostname != inventory_hostname_short %} {{ inventory_hostname_short }}{% endif %} localhost ip6-localhost ip6-loopback"
    state: present
