---
- name: Update the apt cache if older than 2 hrs
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 7200
  tags:
    - security-apt

- name: Upgrade packages for security updates
  ansible.builtin.apt:
    upgrade: safe
  tags:
    - security-apt

- name: Install base packages
  ansible.builtin.apt:
    pkg: "{{ common_base_pkgs }}"
    state: present

- name: Message of the day
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Include hostname tasks
  ansible.builtin.include_tasks: hostname.yml
  tags:
    - hostname

- name: Include ansible_user tasks
  ansible.builtin.include_tasks: ansible_user.yml
  tags:
    - security
